version: "3.7"
services:
  #imagem do micro 01
  micro_01: 
    build:
      args:
        user: Thiago
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - microservices

  #imagem do servidor nginx
  nginx:
    image: nginx:alpine
    #unless-stopped = para caso o container cair ele subir novamente 
    restart: unless-stopped
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/ect/nginx/conf.d/
    networks:
      - microservices

  #imagem para o banco de dados
  db_micro_01:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      #pegamos os dados do .env para ser mais seguro, pois o .env não é enviado para o github expondo nossas informacoes
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}   
    #volumes é para nao perder os dados caso removemos o container
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - microservices

#para fazer os microservices se comunicarem atraves desta rede que criamos
networks:
  microservices: 
    driver: bridge




